### ISSUE TITLE
Be consistent with the various `used` columns

### ISSUE THREAD

**Issue by yhylord** [HFIProgramming/NoticeBoardwith5.3#34]
In the `change_vote_table` migration:
```php
$table->integer('show_result')->default(1); // 1 show 2 no
```
This doesn't make much sense. Why not 0 no 1 show? That's how integers work as booleans, and it's like this in previous migrations.

**Comment by NeverBehave** [comment]
😯 That's my bad. Hold on.

**Comment by Johnny-Schultz** [comment]
#38 fixed
