### ISSUE TITLE
Reconstruct VoteHandler and its related method

### ISSUE THREAD

**Issue by NeverBehave** [HFIProgramming/NoticeBoardwith5.3#8]

**Comment by LinZihong** [comment]
I will do this part(

**Comment by NeverBehave** [comment]
@LinZihong ok

**Comment by NeverBehave** [comment]
code review needed @yhylord

**Comment by yhylord** [comment]
@LinZihong 
1. Add `$this->` before helper methods. Remember this is a class.
2. Check the `$unique` variable in `checkIfAllFilled`. It is undefined.

**Comment by NeverBehave** [comment]
@yhylord fixed, [Vote] seeder required for further test.

**Comment by NeverBehave** [comment]
@yhylord @LinZihong Something goes wrong while handling the ticket request, it looks like something to do with the Auth::check()

**Comment by NeverBehave** [comment]
Something goes wrong in the `verifyAnswers` and its related method. Here is a testing SQL file for your guys to test

[newnotice_2017-03-08.sql.zip](https://github.com/HFIProgramming/NoticeBoardwith5.3/files/826951/newnotice_2017-03-08.sql.zip)

_If possible, please also make `VoteController` a smaller one_
@LinZihong @yhylord

**Comment by NeverBehave** [comment]
#37 fixed
